import type { ReactNode } from "react";
import { ArrowLeft, ArrowUpRight, MapPin, Phone } from "lucide-react";

const source = "https://pizzeria-da-michele-kippenheim.netlify.app/";

function PageFrame({ eyebrow, title, children }: { eyebrow: string; title: ReactNode; children: ReactNode }) {
  return <main className="legal-shell"><header className="legal-topbar"><a className="brand" href="/"><span className="brand-mark">DM</span><span className="brand-copy"><b>RISTORANTE</b><em>DA MICHELE</em></span></a><a className="back-link" href="/"><ArrowLeft size={15} /> Zur Startseite</a></header><section className="legal-hero"><span className="kicker">{eyebrow}</span><h1>{title}</h1><div className="legal-rule" /></section><article className="legal-content">{children}</article><footer className="legal-footer"><span>Ristorante Pizzeria da Michele · Kippenheim</span><div><a href="/impressum">Impressum</a><a href="/datenschutz">Datenschutz</a><a href="/bedingungen">Bedingungen</a></div></footer></main>;
}

export function RestaurantPage() {
  return <PageFrame eyebrow="La nostra storia" title={<>Über uns<br /><i>Da Michele.</i></>}><div className="about-grid"><div><p className="lead-paragraph">Ristorante Pizzeria da Michele in Kippenheim steht für italienische Spezialitäten, eine wunderschöne Terrasse und herzliche Gastfreundschaft.</p><p>Pizza, Pinsa, Pasta und Antipasti werden frisch zubereitet. Im Innenbereich erwartet dich ein warmes, gepflegtes Ambiente; draußen sitzt du geschützt und entspannt im Hof. Geburtstage, Taufen und ähnliche Gesellschaften sind nach Absprache auch außerhalb der regulären Öffnungszeiten möglich.</p><div className="address-card"><MapPin size={18} /><div><strong>Poststraße 16</strong><span>77971 Kippenheim</span><a href="tel:+497825430"><Phone size={14} /> 07825 430</a></div></div></div><img className="about-image" src="/assets/Innen2.jpg" alt="Innenbereich von Ristorante Pizzeria da Michele" /></div><div className="legal-columns"><section><h2>Öffnungszeiten</h2><div className="hours-detail"><p><span>Montag — Sonntag</span><b>17:00 — 21:30</b></p></div></section><section><h2>Unsere Küche</h2><p>Pizza, Pinsa, Pasta und Antipasti — klassisch, herzhaft und direkt für die Abholung geeignet. Frag uns gern nach der aktuellen Karte oder ruf für deine Bestellung an.</p><a className="source-link" href="/">Zur Speisekarte <ArrowUpRight size={14} /></a></section></div></PageFrame>;
}

export function ImpressumPage() {
  return <PageFrame eyebrow="Rechtliche Hinweise" title={<>Impressum<br /><i>Da Michele.</i></>}><p className="legal-intro">Angaben gemäß § 5 TMG</p><div className="legal-columns"><section><h2>Adresse</h2><address>Ristorante Pizzeria da Michele<br />Inhaber: <strong>Vito Bertoldo</strong><br />Poststraße 16<br />77971 Kippenheim<br /><a href="tel:+497825430">Tel. 07825 430</a><br /><a href="mailto:bertoldo2300@gmail.com">bertoldo2300@gmail.com</a></address><h2>Bildnachweise</h2><p>Quellenangaben für die verwendeten Bilder und Grafiken: johema-webdesign · Joachim Herzog.</p></section><section><h2>Haftung für Inhalte</h2><p>Als Diensteanbieter sind wir gemäß § 7 Abs. 1 TMG für eigene Inhalte auf diesen Seiten nach den allgemeinen Gesetzen verantwortlich. Nach §§ 8 bis 10 TMG besteht keine allgemeine Pflicht, übermittelte oder gespeicherte fremde Informationen zu überwachen.</p><h2>Urheberrecht</h2><p>Die durch die Seitenbetreiber erstellten Inhalte und Werke unterliegen dem deutschen Urheberrecht. Vervielfältigung, Bearbeitung und Verwertung außerhalb der gesetzlichen Grenzen bedürfen der Zustimmung des jeweiligen Autors oder Erstellers.</p></section></div><div className="source-note">Inhalte und Kontaktdaten übernommen aus der öffentlichen Kippenheim-Website. Bitte vor dem Livegang rechtlich prüfen.</div></PageFrame>;
}

export function DatenschutzPage() {
  return <PageFrame eyebrow="Rechtliche Hinweise" title={<>Datenschutz<br /><i>auf einen Blick.</i></>}><p className="legal-intro">Der Schutz deiner persönlichen Daten ist uns wichtig. Diese Hinweise orientieren sich an den Informationen der Kippenheimer Restaurant-Website.</p><div className="legal-long"><h2>Verantwortlicher</h2><p>Verantwortlich im Sinne der Datenschutz-Grundverordnung ist:</p><address>Ristorante Pizzeria da Michele<br />Inhaber: Vito Bertoldo<br />Poststraße 16<br />77971 Kippenheim<br /><a href="tel:+497825430">07825 430</a><br /><a href="mailto:bertoldo2300@gmail.com">bertoldo2300@gmail.com</a></address><h2>Bereitstellung der Website</h2><p>Beim Aufruf unserer Website können technisch notwendige Daten wie Browsertyp, Betriebssystem, Internet-Service-Provider, IP-Adresse, Datum und Uhrzeit des Zugriffs sowie aufgerufene Seiten in Logfiles verarbeitet werden. Die Verarbeitung dient der sicheren und funktionsfähigen Bereitstellung der Website und erfolgt auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO.</p><h2>Cookies und Analyse</h2><p>Technisch notwendige Cookies können verwendet werden, um Funktionszustände zu speichern. Analyse-Cookies werden nur auf Grundlage einer Einwilligung eingesetzt. Eine Einwilligung kann jederzeit über die Browsereinstellungen widerrufen werden.</p><h2>Kontakt per E-Mail</h2><p>Wenn du uns per E-Mail kontaktierst, verarbeiten und speichern wir die übermittelten Daten ausschließlich zur Bearbeitung deiner Anfrage. Die Daten werden gelöscht, sobald die Konversation abgeschlossen ist und keine gesetzlichen Aufbewahrungspflichten entgegenstehen.</p><h2>Deine Rechte</h2><p>Du hast insbesondere das Recht auf Auskunft, Berichtigung, Löschung, Einschränkung der Verarbeitung, Datenübertragbarkeit und Widerspruch. Außerdem besteht ein Beschwerderecht bei einer Datenschutzaufsichtsbehörde.</p></div><div className="source-note">Diese Seite ist eine redaktionelle Übernahme und ersetzt keine individuelle Rechtsberatung. Referenz: <a href={source} target="_blank" rel="noreferrer">öffentliche Kippenheim-Website</a>.</div></PageFrame>;
}

export function BedingungenPage() {
  return <PageFrame eyebrow="Rechtliche Hinweise" title={<>Bedingungen<br /><i>für Reservierungen.</i></>}><div className="legal-long"><h2>Geltungsbereich</h2><p>Diese Allgemeinen Geschäftsbedingungen sind Grundlage von Tischreservierungen. Nebenabreden, Vertragsänderungen und Geschäftsbedingungen des Kunden finden nur Anwendung, wenn sie vorher ausdrücklich schriftlich vereinbart wurden.</p><h2>Vertragsschluss</h2><p>Der Vertrag kommt durch die Annahme des Reservierungsantrags durch das Ristorante Da Michele zustande. Mit der Reservierung erklärt sich der Gast verbindlich bereit, zum vereinbarten Zeitpunkt mit der angekündigten Personenzahl zu erscheinen.</p><h2>Stornierungen</h2><p>Ein kostenfreier Rücktritt bedarf der schriftlichen Zustimmung des Ristorante Da Michele, sofern kein gesetzliches oder ausdrücklich vereinbartes Rücktrittsrecht besteht. Bei nicht rechtzeitiger Stornierung oder deutlich geringerer Personenzahl können angemessene Kosten für ungenutzte Aufwendungen entstehen.</p><h2>Verspätungen</h2><p>Ein verspätetes Eintreffen von bis zu 30 Minuten wird toleriert. Danach behalten wir uns vor, reservierte Plätze anderweitig zu vergeben. Bitte kontaktiere uns im Verspätungsfall rechtzeitig.</p><h2>Datenschutz</h2><p>Informationen zur Verarbeitung personenbezogener Daten findest du in unserer <a className="inline-link" href="/datenschutz">Datenschutzerklärung</a>.</p></div><div className="source-note">Übernommen und für diese Website redaktionell strukturiert nach der öffentlichen Kippenheim-Website. Bitte vor Veröffentlichung rechtlich prüfen.</div></PageFrame>;
}
