import type { ReactNode } from "react";
import { ArrowLeft, ArrowUpRight, MapPin, Phone } from "lucide-react";

const source = "https://github.com/da-michele/da-michele.com";

function PageFrame({ eyebrow, title, children }: { eyebrow: string; title: ReactNode; children: ReactNode }) {
  return <main className="legal-shell"><header className="legal-topbar"><a className="brand" href="/"><span className="brand-mark">DM</span><span className="brand-copy"><b>RISTORANTE</b><em>DA MICHELE</em></span></a><a className="back-link" href="/"><ArrowLeft size={15} /> Zur Startseite</a></header><section className="legal-hero"><span className="kicker">{eyebrow}</span><h1>{title}</h1><div className="legal-rule" /></section><article className="legal-content">{children}</article><footer className="legal-footer"><span>Ristorante Da Michele · Baden-Baden</span><div><a href="/impressum">Impressum</a><a href="/datenschutz">Datenschutz</a><a href="/bedingungen">Bedingungen</a></div></footer></main>;
}

export function RestaurantPage() {
  return <PageFrame eyebrow="La nostra storia" title={<>Über uns<br /><i>Da Michele.</i></>}><div className="about-grid"><div><p className="lead-paragraph">Ristorante Da Michele in Baden-Baden steht für große italienische Küche an einem Ort, an dem man sie nicht unbedingt erwartet.</p><p>Unsere täglich wechselnde Karte verbindet frische Fisch- und Fleischgerichte mit den italienischen Klassikern, die man immer wieder essen möchte. In der Küche arbeitet die Familie Romano mit Respekt vor dem Produkt und Freude an der Gastfreundschaft.</p><div className="address-card"><MapPin size={18} /><div><strong>Rheinstr. 109</strong><span>76532 Baden-Baden · Baden-Oos</span><a href="tel:+49722161541"><Phone size={14} /> 07221 — 61541</a></div></div></div><img className="about-image" src="/manus-storage/team_d491b7da.webp" alt="Team von Ristorante Da Michele" /></div><div className="legal-columns"><section><h2>Öffnungszeiten</h2><div className="hours-detail"><p><span>Montag</span><b>12:00 — 14:00</b></p><p><span>Dienstag</span><b>Geschlossen</b></p><p><span>Mittwoch — Samstag</span><b>12:00 — 14:00<br />18:00 — 21:30</b></p><p><span>Sonntag</span><b>18:00 — 21:30</b></p></div></section><section><h2>Unsere Küche</h2><p>Die Karte wird täglich neu gedacht. Fisch, Fleisch, Pasta, Pinsa und saisonales Gemüse bilden die Basis für die Küche von Da Michele. Frag uns gern nach der aktuellen Tageskarte.</p><a className="source-link" href="/">Zur Tageskarte <ArrowUpRight size={14} /></a></section></div></PageFrame>;
}

export function ImpressumPage() {
  return <PageFrame eyebrow="Rechtliche Hinweise" title={<>Impressum<br /><i>Da Michele.</i></>}><p className="legal-intro">Anbieter laut § 5 TMG, § 6 TMG und inhaltlich verantwortlich laut § 55 Abs. 2 RStV-2016.</p><div className="legal-columns"><section><h2>Adresse</h2><address>Ristorante Da Michele<br />Inhaber: <strong>Vincenzo Romano</strong><br />Rheinstr. 109<br />76532 Baden-Baden<br /><a href="tel:+49722161541">Tel. 07221 — 61541</a></address><h2>Unternehmen</h2><p><strong>Firmensitz</strong><br />Baden-Baden</p><p><strong>Gerichtsstand</strong><br />Amtsgericht Mannheim</p><p><strong>Umsatzsteuer-ID</strong><br />DE 33072 / 18023</p></section><section><h2>Verantwortlich</h2><p><strong>Inhaber und inhaltlich verantwortlich</strong><br />Vincenzo Romano</p><p>Wir sind unter der oben angegebenen Adresse erreichbar.</p><h2>Streitbeilegung</h2><p>Wir sind zur Teilnahme an einem Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle nicht verpflichtet und nehmen daran nicht teil.</p><p>Die Online-Streitbeilegungsplattform der EU-Kommission findest du unter <a className="inline-link" href="https://ec.europa.eu/consumers/odr" target="_blank" rel="noreferrer">ec.europa.eu/consumers/odr</a>.</p><h2>Urheberrecht</h2><p>Die auf dieser Website veröffentlichten Inhalte sind rechtlich unter anderem durch das Urheberrecht geschützt.</p></section></div><div className="source-note">Inhalte und Kontaktdaten übernommen aus der öffentlichen Da-Michele-Website und dem zugehörigen <a href={source} target="_blank" rel="noreferrer">GitHub-Repository</a>. Bitte vor dem Livegang rechtlich prüfen.</div></PageFrame>;
}

export function DatenschutzPage() {
  return <PageFrame eyebrow="Rechtliche Hinweise" title={<>Datenschutz<br /><i>auf einen Blick.</i></>}><p className="legal-intro">Der Schutz deiner persönlichen Daten ist uns wichtig. Die folgenden Hinweise orientieren sich an der öffentlich veröffentlichten Datenschutzerklärung von Ristorante Da Michele.</p><div className="legal-long"><h2>Verantwortlicher</h2><p>Verantwortlich im Sinne der Datenschutz-Grundverordnung ist:</p><address>Ristorante Da Michele<br />Inhaber: Vincenzo Romano<br />Rheinstr. 109<br />76532 Baden-Baden<br /><a href="tel:+49722161541">07221 — 61541</a></address><h2>Bereitstellung der Website</h2><p>Beim Aufruf unserer Website können technisch notwendige Daten wie Browsertyp, Betriebssystem, Internet-Service-Provider, IP-Adresse, Datum und Uhrzeit des Zugriffs sowie aufgerufene Seiten in Logfiles verarbeitet werden. Die Verarbeitung dient der sicheren und funktionsfähigen Bereitstellung der Website und erfolgt auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO. Logfiles werden grundsätzlich spätestens nach sieben Tagen gelöscht oder anonymisiert.</p><h2>Cookies und Analyse</h2><p>Technisch notwendige Cookies können verwendet werden, um Spracheinstellungen, Suchbegriffe oder Funktionszustände zu speichern. Analyse-Cookies werden nur auf Grundlage einer Einwilligung eingesetzt. Eine Einwilligung kann jederzeit über die Browsereinstellungen widerrufen werden.</p><h2>Kontakt per E-Mail</h2><p>Wenn du uns per E-Mail kontaktierst, verarbeiten und speichern wir die übermittelten Daten ausschließlich zur Bearbeitung deiner Anfrage. Die Daten werden gelöscht, sobald die Konversation abgeschlossen ist und keine gesetzlichen Aufbewahrungspflichten entgegenstehen.</p><h2>Deine Rechte</h2><p>Du hast insbesondere das Recht auf Auskunft, Berichtigung, Löschung, Einschränkung der Verarbeitung, Datenübertragbarkeit und Widerspruch. Außerdem besteht ein Beschwerderecht bei einer Datenschutzaufsichtsbehörde.</p></div><div className="source-note">Diese Seite ist eine redaktionelle Übernahme und ersetzt keine individuelle Rechtsberatung. Vollständige Referenz: <a href={source} target="_blank" rel="noreferrer">öffentliches Repository</a>.</div></PageFrame>;
}

export function BedingungenPage() {
  return <PageFrame eyebrow="Rechtliche Hinweise" title={<>Bedingungen<br /><i>für Reservierungen.</i></>}><div className="legal-long"><h2>Geltungsbereich</h2><p>Diese Allgemeinen Geschäftsbedingungen sind Grundlage von Tischreservierungen. Nebenabreden, Vertragsänderungen und Geschäftsbedingungen des Kunden finden nur Anwendung, wenn sie vorher ausdrücklich schriftlich vereinbart wurden.</p><h2>Vertragsschluss</h2><p>Der Vertrag kommt durch die Annahme des Reservierungsantrags durch das Ristorante Da Michele zustande. Mit der Reservierung erklärt sich der Gast verbindlich bereit, zum vereinbarten Zeitpunkt mit der angekündigten Personenzahl zu erscheinen.</p><h2>Stornierungen</h2><p>Ein kostenfreier Rücktritt bedarf der schriftlichen Zustimmung des Ristorante Da Michele, sofern kein gesetzliches oder ausdrücklich vereinbartes Rücktrittsrecht besteht. Bei nicht rechtzeitiger Stornierung oder deutlich geringerer Personenzahl können angemessene Kosten für ungenutzte Aufwendungen entstehen.</p><h2>Verspätungen</h2><p>Ein verspätetes Eintreffen von bis zu 30 Minuten wird toleriert. Danach behalten wir uns vor, reservierte Plätze anderweitig zu vergeben. Bitte kontaktiere uns im Verspätungsfall rechtzeitig.</p><h2>Datenschutz</h2><p>Informationen zur Verarbeitung personenbezogener Daten findest du in unserer <a className="inline-link" href="/datenschutz">Datenschutzerklärung</a>.</p></div><div className="source-note">Übernommen und für diese Website redaktionell strukturiert nach der öffentlichen Fassung im <a href={source} target="_blank" rel="noreferrer">Da-Michele-GitHub-Repository</a>. Bitte vor Veröffentlichung rechtlich prüfen.</div></PageFrame>;
}
